### ISSUE TITLE
Creating users "hangs"

### ISSUE THREAD

**Issue by terle** [terle/NoitsoHinterBahnApp#5]

**Comment by darwind** [comment]
Easy fix would be to implement a progressdialog, which I think we should do at first.

Progressdialog should be at the CreateUserActivity view.

**Comment by darwind** [comment]
http://notes.theorbis.net/2010/02/batch-insert-to-sqlite-on-android.html

**Comment by darwind** [comment]
Fixed by using transactions on the database.
The reason for transactions being faster is that every time an insertion occurs a temporary file is created on the device. This file holds informations about the insertion to happen. The file is then read and deleted. If we insert 20 times, we create, read and delete 20 files. This is the "bottleneck". So when using transactions, we create ONE file and write to this file ONCE (because the file will be opened until we're done writing to it in out transaction). Afterwards we read the file ONCE and hence delete it ONCE.

IO is simply slow and should be avoided at all cost ;-)
